import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    backgroundColor: "#f3f7f6",
    flex: 1,
  },
  header: {
    backgroundColor: "#113f45",
    paddingBottom: 24,
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  headerRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  iconButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 8,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  headerTitle: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "900",
    marginTop: 18,
  },
  headerSubtitle: {
    color: "#c7dddc",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
  },
  content: {
    padding: 16,
    paddingBottom: 36,
  },
  loadingWrap: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
  },
  emptyCard: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#dce8e6",
    borderRadius: 8,
    borderWidth: 1,
    padding: 22,
  },
  emptyTitle: {
    color: "#173b40",
    fontSize: 17,
    fontWeight: "900",
    marginTop: 12,
  },
  emptyText: {
    color: "#6b7f82",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 6,
    textAlign: "center",
  },
  accountCard: {
    backgroundColor: "#ffffff",
    borderColor: "#dce8e6",
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 12,
    overflow: "hidden",
  },
  accountCardActive: {
    borderColor: "#1d7477",
  },
  accountButton: {
    alignItems: "center",
    flexDirection: "row",
    minHeight: 82,
    padding: 15,
  },
  avatar: {
    alignItems: "center",
    backgroundColor: "#e6f5ef",
    borderRadius: 8,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  avatarText: {
    color: "#176564",
    fontSize: 17,
    fontWeight: "900",
  },
  accountInfo: {
    flex: 1,
    marginLeft: 12,
    paddingRight: 8,
  },
  accountName: {
    color: "#173b40",
    fontSize: 16,
    fontWeight: "900",
  },
  accountEmail: {
    color: "#667d80",
    fontSize: 12,
    marginTop: 3,
  },
  permissionCount: {
    color: "#1d7477",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 5,
  },
  editor: {
    backgroundColor: "#f7fbfa",
    borderTopColor: "#edf3f2",
    borderTopWidth: 1,
    padding: 15,
  },
  editorTitle: {
    color: "#173b40",
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 10,
  },
  permissionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  permissionCard: {
    alignItems: "flex-start",
    backgroundColor: "#f8fbfb",
    borderColor: "#d7e5e3",
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 112,
    padding: 12,
    width: "48%",
  },
  permissionCardActive: {
    backgroundColor: "#e6f5ef",
    borderColor: "#2f9c72",
  },
  permissionIcon: {
    height: 28,
    marginBottom: 9,
    width: 28,
  },
  permissionTextWrap: {
    flex: 1,
  },
  permissionTitle: {
    color: "#1f3f43",
    fontSize: 13,
    fontWeight: "800",
  },
  permissionDescription: {
    color: "#6b7f82",
    fontSize: 11,
    lineHeight: 15,
    marginTop: 2,
  },
  checkBadge: {
    alignItems: "center",
    backgroundColor: "#2f9c72",
    borderRadius: 10,
    height: 20,
    justifyContent: "center",
    position: "absolute",
    right: 10,
    top: 10,
    width: 20,
  },
  saveButton: {
    alignItems: "center",
    backgroundColor: "#1c6f73",
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 14,
    minHeight: 48,
  },
  saveButtonDisabled: {
    backgroundColor: "#9bb8b8",
  },
  saveText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
    marginLeft: 8,
  },
});

export default styles;
