import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    backgroundColor: "#f4f7f6",
    flex: 1,
  },
  header: {
    backgroundColor: "#103f45",
    paddingBottom: 46,
    paddingHorizontal: 18,
    paddingTop: 18,
  },
  headerTop: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  iconButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.13)",
    borderRadius: 8,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  headerTitleWrap: {
    alignItems: "center",
    flex: 1,
  },
  headerEyebrow: {
    color: "#9fd0c8",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  headerTitle: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "900",
    marginTop: 2,
  },
  welcomeBlock: {
    marginTop: 30,
  },
  roleBadge: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.12)",
    borderColor: "rgba(255,255,255,0.16)",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  roleBadgeText: {
    color: "#dff8f3",
    fontSize: 12,
    fontWeight: "800",
  },
  welcomeText: {
    color: "#ffffff",
    fontSize: 25,
    fontWeight: "900",
    lineHeight: 31,
    marginTop: 14,
  },
  welcomeSubText: {
    color: "#c9dfdd",
    fontSize: 14,
    lineHeight: 21,
    marginTop: 8,
    maxWidth: 350,
  },
  content: {
    padding: 16,
    paddingBottom: 36,
  },
  primaryAction: {
    alignItems: "center",
    backgroundColor: "#1d7477",
    borderRadius: 8,
    flexDirection: "row",
    gap: 13,
    marginTop: -38,
    minHeight: 92,
    padding: 16,
    shadowColor: "#0b2f34",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 14,
    elevation: 4,
  },
  primaryActionIcon: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.16)",
    borderRadius: 8,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  primaryActionBody: {
    flex: 1,
  },
  primaryActionTitle: {
    color: "#ffffff",
    fontSize: 17,
    fontWeight: "900",
  },
  primaryActionText: {
    color: "#d7eeee",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 5,
  },
  shortcutRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 14,
  },
  shortcutButton: {
    backgroundColor: "#ffffff",
    borderColor: "#dce8e6",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 108,
    padding: 13,
  },
  shortcutIconReview: {
    alignItems: "center",
    backgroundColor: "#e9f5f3",
    borderRadius: 8,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  shortcutIconProfile: {
    alignItems: "center",
    backgroundColor: "#fff2e0",
    borderRadius: 8,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  shortcutTitle: {
    color: "#163b3f",
    fontSize: 15,
    fontWeight: "900",
    marginTop: 10,
  },
  shortcutText: {
    color: "#6c8184",
    fontSize: 12,
    lineHeight: 16,
    marginTop: 4,
  },
  statsRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 14,
  },
  statCard: {
    backgroundColor: "#edf3f2",
    borderColor: "#dbe7e5",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 76,
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  statValue: {
    color: "#143d42",
    fontSize: 21,
    fontWeight: "900",
  },
  statLabel: {
    color: "#647b7e",
    fontSize: 12,
    lineHeight: 16,
    marginTop: 5,
  },
  sectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    marginTop: 24,
  },
  sectionTitle: {
    color: "#163b3f",
    fontSize: 20,
    fontWeight: "900",
  },
  sectionSubtitle: {
    color: "#6e8386",
    fontSize: 13,
    marginTop: 3,
  },
  sectionCount: {
    backgroundColor: "#e5f1ef",
    borderRadius: 8,
    color: "#1d5f66",
    fontSize: 13,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  formList: {
    gap: 10,
  },
  formRow: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#dce8e6",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    minHeight: 76,
    paddingHorizontal: 13,
    paddingVertical: 12,
  },
  formIconWrap: {
    alignItems: "center",
    backgroundColor: "#edf7f5",
    borderRadius: 8,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  formIcon: {
    height: 28,
    width: 28,
  },
  formTextWrap: {
    flex: 1,
    marginLeft: 12,
    paddingRight: 8,
  },
  formTitle: {
    color: "#173b40",
    fontSize: 15,
    fontWeight: "900",
  },
  formDescription: {
    color: "#73878a",
    fontSize: 12,
    lineHeight: 16,
    marginTop: 4,
  },
});

export default styles;
