export const JOTFORM_REGISTER_FORM_ID = "251982343900154";
export const JOTFORM_REGISTER_SUBMIT_URL =
  "https://hipaa-submit.jotform.com/submit/251982343900154";

export const JOTFORM_REGISTER_FIELD_MAP = {
  status: "q374_status",
  plan: "q9_name9[]",
  serviceEvent: "q416_serviceevent[]",
  employerCode: "q378_code",
  driverLicensePrimary: "q421_driverLicense",
  driverLicenseSecondary: "q16_driverLicense16",
  companyName: "q3_companyName3",
  driverPhone: "q333_driverPhone[full]",
  companyCity: "q316_companyCity",
  companyAddress: "q315_companyAddress",
  companyEmail: "q8_companyEmail",
  companyState: "q317_companyState",
  companyZip: "q318_companyZip",
  usdot: "q15_usdot",
  mcNumber: "q7_mc",
  derFirstName: "q363_derFirst",
  derLastName: "q314_derLast314",
  driverFirstNamePrimary: "q352_driverFirst352",
  driverFirstNameSecondary: "q10_driverFirst",
  driverLastName: "q320_driverLast",
  driverEmail: "q339_driverEmail",
  driverAddress: "q334_driverStreet",
  driverCity: "q335_driverCity",
  driverState: "q336_driverState",
  driverZip: "q337_driverZip",
  driverStateLicenseIssue: "q338_driverState338",
  dateOfBirth: "q369_dateOf369",
  dateOfEnrollmentMonth: "q12_dateOf[month]",
  dateOfEnrollmentDay: "q12_dateOf[day]",
  dateOfEnrollmentYear: "q12_dateOf[year]",
  dateOfExpirationMonth: "q17_dateOf17[month]",
  dateOfExpirationDay: "q17_dateOf17[day]",
  dateOfExpirationYear: "q17_dateOf17[year]",
  witness: "q328_witness",
  signDateMonth: "q21_signDate[month]",
  signDateDay: "q21_signDate[day]",
  signDateYear: "q21_signDate[year]",
} as const;
