import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f4f7fb",
  },
  scroll: {
    paddingBottom: 36,
  },
  header: {
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 18,
    backgroundColor: "#f4f7fb",
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  navButton: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#10243f",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
  },
  navButtonMuted: {
    backgroundColor: "#173c63",
  },
  brandWrap: {
    flex: 1,
    paddingHorizontal: 16,
  },
  brandEyebrow: {
    color: "#698099",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  brandTitle: {
    color: "#14304d",
    fontSize: 20,
    fontWeight: "800",
    marginTop: 4,
  },
  heroCard: {
    marginTop: 18,
    backgroundColor: "#173c63",
    borderRadius: 28,
    padding: 22,
    overflow: "hidden",
  },
  heroGlowOne: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.08)",
    top: -40,
    right: -30,
  },
  heroGlowTwo: {
    position: "absolute",
    width: 120,
    height: 120,
    borderRadius: 999,
    backgroundColor: "rgba(116, 194, 255, 0.14)",
    bottom: -30,
    right: 40,
  },
  heroLabel: {
    color: "#a9c5df",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  heroTitle: {
    color: "#ffffff",
    fontSize: 26,
    lineHeight: 32,
    fontWeight: "800",
    marginTop: 10,
    maxWidth: 220,
  },
  heroSubtitle: {
    color: "#d5e5f2",
    fontSize: 14,
    lineHeight: 21,
    marginTop: 10,
    maxWidth: 260,
  },
  heroMetaRow: {
    flexDirection: "row",
    marginTop: 18,
    gap: 10,
    flexWrap: "wrap",
  },
  heroMetaCard: {
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minWidth: 110,
  },
  heroMetaLabel: {
    color: "#a9c5df",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  heroMetaValue: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
    marginTop: 4,
  },
  section: {
    paddingHorizontal: 20,
    marginTop: 24,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 14,
  },
  sectionTitle: {
    color: "#163250",
    fontSize: 20,
    fontWeight: "800",
  },
  sectionHint: {
    color: "#75879b",
    fontSize: 12,
    fontWeight: "600",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 14,
  },
  quickActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 4,
  },
  quickActionCard: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 16,
    shadowColor: "#10243f",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 3,
  },
  quickActionTitle: {
    color: "#163250",
    fontSize: 15,
    fontWeight: "800",
  },
  quickActionText: {
    color: "#708397",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 6,
  },
});

export default styles;
