export const TabScreens = {
  index: "index",
  history: "history",
};

export const StackScreens = {
  login: "Login",
  home: "homeScreen",
  renewStepOne: "renewStepOneScreen",
  renewStepTwo: "renewStepTwoScreen",
  renewStepThree: "renewStepThreeScreen",
  renewFinalStep: "renewFinalStepScreen",
  randomStepOne: "randomStepOneScreen",
  randomStepTwo: "randomStepTwoScreen",
  profile: "profileScreen",
  changePassword: "changePasswordScreen",
  term: "termScreen",
  register: "registerScreen",
  sms: "smsScreen",
  forgotPassword: "forgotPasswordScreen",
  medicalCertificateStepOne: "medicalCertificateStepOneScreen",
  medicalCertificateStepTwo: "medicalCertificateStepTwoScreen",
  medicalCertificateStepThree: "medicalCertificateStepThreeScreen",
  medicalCertificateQuestionListStepOne: "medicalCertificateQuestionListStepOneScreen",
  medicalCertificateQuestionListStepTwo: "medicalCertificateQuestionListStepTwoScreen",
  medicalCertificateQuestionListStepThree: "medicalCertificateQuestionListStepThreeScreen",
  medicalCertificateStepFour: "medicalCertificateStepFourScreen",
  medicalCertificateDrStepOne: "medicalCertificateDrStepOneScreen",
  medicalCertificateDrStepTwo: "medicalCertificateDrStepTwoScreen",
  medicalCertificateDrStepThree: "medicalCertificateDrStepThreeScreen",
  medicalCertificateDrStepFour: "medicalCertificateDrStepFourScreen",
  medicalCertificateDrStepFive: "medicalCertificateDrStepFiveScreen",
  drugTestStepOne: "drugTestStepOneScreen",
  drugTestStepTwo: "drugTestStepTwoScreen",
  drugTestStepThree: "drugTestStepThreeScreen",
  drugTestFinalStep: "drugTestFinalStepScreen",
  returnDutyStepOne: "returnDutyStepOneScreen",
  returnDutyStepTwo: "returnDutyStepTwoScreen",
  returnDutyStepThree: "returnDutyStepThreeScreen",
  returnDutyFinalStep: "returnDutyFinalStepScreen",
  followUpStepOne: "followUpStepOneScreen",
  followUpStepTwo: "followUpStepTwoScreen",
  followUpStepThree: "followUpStepThreeScreen",
  followUpFinalStep: "followUpFinalStepScreen",
  hairTestStepOne: "hairTestStepOneScreen",
  hairTestStepTwo: "hairTestStepTwoScreen",
  hairTestStepThree: "hairTestStepThreeScreen",
  hairTestFinalStep: "hairTestFinalStepScreen",
  postAccidentStepOne: "postAccidentStepOneScreen",
  postAccidentStepTwo: "postAccidentStepTwoScreen",
  postAccidentStepThree: "postAccidentStepThreeScreen",
  postAccidentFinalStep: "postAccidentFinalStepScreen",
  registerStepOne: "registerStepOneScreen",
  registerStepTwo: "registerStepTwoScreen",
  registerFinalStep: "registerFinalStepScreen",
  question: "questionScreen",
  employer: "employerScreen",
  adminHome: "admins/adminHomeScreen",
  adminProfileCheck: "admins/adminProfileCheckScreen",
  adminCreateSubAccount: "admins/adminCreateSubAccountScreen",
};

export const Screens = {
  auth: "(auths)",
  tab: "(tabs)",
  adminTab: "(adminTabs)",
  index: "index",
};
